### ISSUE TITLE
Explain instant profile

### ISSUE THREAD

**Issue by Iaotle** [Haselnussbomber/HaselTweaks#1]
Not sure what it does currently. What's an instant profile?

**Comment by Haselnussbomber** [comment]
Haha, that is actually a really good typo from me, that i'll fix right away. I mean the new Instant Portraits, of course! 😅 
So whenever you extract materia or change your gear and click the button to update the gearset it would've unlinked the instant portrait. I removed that part of the function, so it keeps being linked.
But i haven't actually figured out if there are any sideeffects.

**Comment by Haselnussbomber** [comment]
I pushed a new version (v0.0.7) and renamed the tweak, so you have to re-enable it, as it doesn't automatically do that. 😉

**Comment by Iaotle** [comment]
By instant portrait do you mean the adventurer plate?

**Comment by Haselnussbomber** [comment]
No, this has nothing to do with the adventurer plate.
You can set a portrait as instant portrait which "are used to introduce players at the start of various duties. As of Patch 6.1, they are used to introduce combatants at the beginning of Crystalline Conflict PvP matches." (From the [Patch Notes](https://eu.finalfantasyxiv.com/lodestone/topics/detail/808eb196b065ebd1b6ec130fac1402d99f7f90a4))

You can either set a single one as instant portrait for all your jobs (screenshot from google):

![Image](https://www.mmogah.com/Public/news/portrait.jpg)

Or when you rightclick a gearset you can link each gearset to its own portrait.

![ffxiv_dx11_2022-04-25_04-07-25](https://user-images.githubusercontent.com/96642047/165009134-377834bf-41c0-4e86-b1fa-16ac8b498e70.png)
