### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by zflr** [Haselnussbomber/HaselTweaks#100]
![捕获](https://github.com/Haselnussbomber/HaselTweaks/assets/124473956/326b8fe1-437e-421b-b6ce-0ed808a74863)
![捕获](https://github.com/Haselnussbomber/HaselTweaks/assets/124473956/47d8af4e-5345-4fb0-a2b7-515177afd979)

**Comment by Haselnussbomber** [comment]
I contributed a lot of my structs to https://github.com/aers/FFXIVClientStructs 3 weeks ago, which was released with Dalamud 9.1.0.8 last week.
If you're using an outdated Dalamud fork, please request an update there.
