### ISSUE TITLE
[Enhanced Isleworks Agenda] Search bar now remembers last entry after 6/20 update

### ISSUE THREAD

**Issue by Faieee** [Haselnussbomber/HaselTweaks#106]
Before the update: Clicking to add an item to a day's agenda would open up a fresh search box, sending every keyboard input to that search box. Pressing enter would add the item to your agenda and close the search box.

After the update: Clicking to add an item to a day's agenda opens up a search box _that has the contents of the last search still in it_. Your keyboard inputs are _not_ sent to the search box without first manually clicking on the search box, at which point you must delete the old contents of the search box to look up a new item. Pressing enter properly adds the item and closes the search box.

This is counterproductive behavior since a player will never have the need to search for the same item multiple times, therefore there is no reason to remember the last search string. The new functionality of _not_ focusing the search bar for your keyboard inputs also adds an unnecessary step of having to click on the search box, something the previous version of the plugin did for you.

**Comment by Haselnussbomber** [comment]
Ah, yeah, I’ll fix it soon. Sorry!

**Comment by Haselnussbomber** [comment]
Thanks for reporting this!
I'm currently restructuring my code, so I had this bug snuck in.
It's fixed now with [v24.0.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v24.0.1). :)
