### ISSUE TITLE
Add option not to warn if DoH/DoL portrait breaks

### ISSUE THREAD

**Issue by Zumurrud** [Haselnussbomber/HaselTweaks#112]
Being notified when my portrait is broken is fantastic.

However, I get a fair number of nuisance warnings when I change my crafter and gatherer gearsets.  I don't really care if their portraits break, since I've never seen them displayed in-game.

It's possible to create & update basic portraits to avoid getting warnings (and I have been), but it'd be nice if I could silence the warnings from those jobs.

**Comment by Haselnussbomber** [comment]
Added with [v25.1.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.1.0). 🙂
