### ISSUE TITLE
Warn after instance if portrait is broken

### ISSUE THREAD

**Issue by Zumurrud** [Haselnussbomber/HaselTweaks#113]
Consider the following sequence of events:
1. Enter instance
2. Update gearset, e.g. after winning some gear
 -> HaselTweaks warns that your portrait is broken, but you can't update your portrait in an instance
3. Leave instance
4. Queue for a second instance
5. Enter second instance and receive dreaded "Instant portrait reverted to default" message

In my case I did a dungeon, got some gear from the first boss, updated my gearset, left the instance 15ish minutes later, and queued again after forgetting that my portrait was already broken.

It would be nice if HaselTweaks could check for broken portraits upon queuing (though perhaps this'd make it difficult to fix portraits in time, if the queue pops immediately) or immediately after leaving an instance (or anywhere else it's impossible to update a portrait?).

**Comment by Zumurrud** [comment]
I don't know if this is worth addressing, but it has bitten me at least once, so I figured I'd put in an issue and let you decide. 🫡

**Comment by Haselnussbomber** [comment]
Great idea! I released [v25.1.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.1.1), which delays the check until after leaving the duty.
I hope this works without problems, as I've only tested it briefly. 😅

**Comment by Zumurrud** [comment]
In my own limited testing, it seems to work great, ha.  I'm happy to call it closed for now.

Thanks so much!  This helper keeps saving me from the ignominy of a DMV portrait, and this change closes a gap in its defenses.
