### ISSUE TITLE
[Feature Request] "Search the markets" from Gathering Log

### ISSUE THREAD

**Issue by drejjmit** [Haselnussbomber/HaselTweaks#114]
Would it be possible to get "Search the markets" context shortcut in Gathering Log?

![image](https://github.com/user-attachments/assets/7ef57066-94c6-4cdf-8264-367ed005d245)

**Comment by Haselnussbomber** [comment]
Yep, added in [v25.2.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.2.0). 🙂
