### ISSUE TITLE
[Feature Request] DTR - Custom FPS Text Improvement

### ISSUE THREAD

**Issue by ZohiDev** [Haselnussbomber/HaselTweaks#115]
Currently the custom text for FPS can only be appended to the end of the actual FPS value. It would be nice if we could specify where in the string we'd like the value to appear, maybe with some character like %% etc so that something like "test 60fps test" would be possible.

Thanks for your time!

**Comment by Haselnussbomber** [comment]
I've released [v25.2.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.2.1), in which you can now set the format that is passed to C#s string.Format function.
The first argument is the fps value, which is inserted with `{0}`.

**Comment by ZohiDev** [comment]
Thank you so much!
