### ISSUE TITLE
Crash when disabling plugin

### ISSUE THREAD

**Issue by 0xMOPI** [Haselnussbomber/HaselTweaks#117]
FFXIV crashes every time I disable the plugin, this also means when I close the game it ends up crashing as well.
[dalamud_appcrash_20240717_192822_432_32784.log](https://github.com/user-attachments/files/16275333/dalamud_appcrash_20240717_192822_432_32784.log)
[dalamud.log](https://github.com/user-attachments/files/16275335/dalamud.log)
[crash-20240717192903.zip](https://github.com/user-attachments/files/16275337/crash-20240717192903.zip)

**Comment by Haselnussbomber** [comment]
Thanks for reporting!
This happened due to a recent change in Dalamud (staging). I informed them about it and it got fixed immediately.
Please restart your game to update Dalamud. 🙂
