### ISSUE TITLE
Auto Sorter not working on non-English clients

### ISSUE THREAD

**Issue by beckyeeky** [Haselnussbomber/HaselTweaks#119]
Tried with JP clients, and only the rules of saddlebag (left side only) responds to execution button.

**Comment by Haselnussbomber** [comment]
Ah, I re-wrote some code and forgot to pass the client language when getting the /isort parameters from the sheet. It used the language set in Dalamud instead.
Fixed with [v25.2.6](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.2.6). :)
