### ISSUE TITLE
[Expert Deliveries] resets the selection to first item after delivering

### ISSUE THREAD

**Issue by jacob-keller** [Haselnussbomber/HaselTweaks#120]
If [Expert Deliveries] is enabled, after delivering an item, the window will be reset to the first item in the list. The normal behavior without this tweak is to maintain the position in the list of possible turn ins. This makes [Expert Deliveries] less useful for me, as I routinely avoid turning some stuff in as I identify that it could be desynthesized or otherwise I wish to keep the item.

**Comment by Haselnussbomber** [comment]
Yeah, makes sense. I don't check if the window is already on the Expert Delivery tab before calling that it should change the tab when the window opens.
That's an easy fix. Coming soon!

**Comment by Haselnussbomber** [comment]
Should be fixed now with [v25.2.7](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.2.7). 🙂
