### ISSUE TITLE
[Aether Current Helper] Feature request: Sort aether currents by distance

### ISSUE THREAD

**Issue by alyssadev** [Haselnussbomber/HaselTweaks#121]
Please add a checkbox to toggle whether aether currents are sorted by distance from the player, rather than their ingame numbering.

**Comment by Haselnussbomber** [comment]
That would require a complete rewrite of all the drawing logic in the window, so I'm sorry but it's not worth my time.
I recommend getting Umbra, which will draw 3D markers when you are near an aether current.
