### ISSUE TITLE
Window refuse to stay in cluster

### ISSUE THREAD

**Issue by Dajova** [Haselnussbomber/HaselTweaks#124]
I have a macro there i open 3 windows at once, all in the same window cluster (tabs)... but this plugins window refuses to stay in the cluster after relogging. Do you have a default position that is defaulted back to its origin place or something? If so, can you remove it?

**Comment by Haselnussbomber** [comment]
Which window and what's a window cluster?

**Comment by Dajova** [comment]
The main window of the plugin. It wont stay in the main window where i put it after restart.

![image](https://i.imgur.com/th5z7A8.png)
This is how it looks like on login.

![image](https://i.imgur.com/7j6Utwu.png)
This is how i want it to behave, but it resets to previous location on restart.

**Comment by Haselnussbomber** [comment]
I changed the flags on the window. Please update to [v25.2.11](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.2.11) and see if it's fixed. :)

**Comment by Dajova** [comment]
> I changed the flags on the window. Please update to [v25.2.11](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v25.2.11) and see if it's fixed. :)

tested and confirmed, it now correctly stays in place with the other windows :)
