### ISSUE TITLE
[Portrait Helper] Update Gearset while Gearset Switcher open

### ISSUE THREAD

**Issue by NevendyND** [Haselnussbomber/HaselTweaks#125]
When you update your gearset while your Gearset Switcher is open it goes instant at the start to Gearset 1 and doesn't stay at the Gearset what you were updating.

Behavior feels like the Plugin thinks the Gearset Switcher gets open for the first time.

**Comment by Haselnussbomber** [comment]
I'm sorry, but I don't know what you mean.
Do you mean "Gear Set Grid" with "Gearset Switcher"? And why did you tag this with Portrait Helper?

**Comment by NevendyND** [comment]
I tagged Portrait Helper because it only happens when i have it enabled.
![image](https://github.com/user-attachments/assets/c3361e00-3a2e-4ed3-a5fa-9f14d81b9891)
Here a Video that explains it better, sorry me English is not the best.
https://github.com/user-attachments/assets/adc06282-26bd-4914-92d2-4e3f7f83462a

**Comment by Haselnussbomber** [comment]
Wir können auch in Deutsch schreiben! :)
Ich versteh jetzt was du meinst, kann das auch nachstellen und weiß auch wo das Problem auftritt, allerdings bin ich mir grade noch unsicher *warum* das so passiert. Wird wohl etwas dauern.^^

**Comment by NevendyND** [comment]
Ah, tut mir leid, das war mir nicht bewusst.
Es freut mich jedenfalls dass ich das "Problem" doch irgendwie beschreiben konnte.
Vielen Dank für deine Mühe!

**Comment by Haselnussbomber** [comment]
Sorry für die verspätete Antwort. Ich hab noch versucht ein anderes Problem zu lösen, aber es stellte sich heraus, dass es ein Problem in Dalamud ist.

Bezüglich dieses Problems hier: die Funktion, in die ich mich reinklinke, hat einen falschen Rückgabetyp in ClientStructs (`void` statt `int`) und dadurch aktualisiert sich die gesamte Liste und scrollt nach oben.
Ich hab die Funktion mit korrektem Rückgabetyp temporär in meinem Plugin intetriert, aber wenn du andere Plugins hast, die die Funktion via ClientStructs hooken, dann nützt es auch nichts. Da muss dann Dalamud und die entsprechenden Plugins geupdated werden.

Jedenfalls ist das Problem bei mir mit [v26.0.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v26.0.1) jetzt erstmal erledigt. 🙂

Danke fürs Bescheid sagen!
