### ISSUE TITLE
initialization failure

### ISSUE THREAD

**Issue by zhouhuichen741** [Haselnussbomber/HaselTweaks#128]
![QQ截图20240928050539](https://github.com/user-attachments/assets/fa51e5e9-60c6-4213-bbcc-e921edf02edc)
![QQ截图20240928050621](https://github.com/user-attachments/assets/5838bca2-4f99-4c76-a18b-d764626024a2)

**Comment by Haselnussbomber** [comment]
This plugin is for the global client (Dawntrail). I can't and won't support any other client, sorry.
