### ISSUE TITLE
[Portrait Helper] Animation Timestamp cannot seek backwards

### ISSUE THREAD

**Issue by Scrxtchy** [Haselnussbomber/HaselTweaks#134]
Not exactly #83 but feels adjacent to it
When attempting to seek backwards, the animation does not respect the adjusted value and resets to the initial timestamp.
Seeking forward still works, which makes it a one-way adjustment when seeking back to the left

**Comment by Haselnussbomber** [comment]
Yeah, I never found a way to fully control the animation.
From what I can see, the functions I call are still the same, so not sure there.
Have to look into it more in-depth, but probably not anytime soon, sorry.

**Comment by Haselnussbomber** [comment]
Well, you got me. Fixed in [v28.0.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v28.0.1).
If not, leave a message.^^
