### ISSUE TITLE
Enhanced Login/Logout prevents Lifestream from selecting character

### ISSUE THREAD

**Issue by YsEmei** [Haselnussbomber/HaselTweaks#135]
``Enhanced Login/Logout`` prevents Lifestream from selecting a character. Even with all options off in ``Enhanced Login/Logout``, just turning the option on prevents it from world traveling in character select.

https://github.com/user-attachments/assets/5dbbcb3a-4bb4-4e94-975c-c7b542133ed4

Worked fine before 7.1 update.
Does this tweak now prevent other plugins from using game functions? Selecting a character.

**Comment by Haselnussbomber** [comment]
I don’t know what Lifestream is. Everything works fine here.

**Comment by Haselnussbomber** [comment]
Just checked, the function my plugin hooks is still the same as before 7.1.
So maybe your other plugin doesn't work because the fields in AgentLobby aren't updated yet.

**Comment by YsEmei** [comment]
Fixed in v28.0.3
Thank you
