### ISSUE TITLE
can not work

### ISSUE THREAD

**Issue by Kochke** [Haselnussbomber/HaselTweaks#138]
It cannot be installed or deleted(cn server ver 7.05)
[crash-20241122213143.zip](https://github.com/user-attachments/files/17870852/crash-20241122213143.zip)
[dalamud_appcrash_20241022_065340_149_20304.log](https://github.com/user-attachments/files/17870855/dalamud_appcrash_20241022_065340_149_20304.log)
[dalamud.log](https://github.com/user-attachments/files/17870856/dalamud.log)

**Comment by Haselnussbomber** [comment]
This plugin is for Dalamud API 11, targeting game version 7.1. I do not support the CN version.
