### ISSUE TITLE
Closing Aether Current window while Aether Current Helper is open causes Helper to get wide

### ISSUE THREAD

**Issue by Gazzoo-byte** [Haselnussbomber/HaselTweaks#14]
As per title, if I close the native Aether Current window, the Helper window from this plugin just gets wider and wider until it consumes my whole monitor

**Comment by Haselnussbomber** [comment]
Yeah, I definitely have seen this problem during development. I'm not sure why it's doing that for you, because it doesn't do it for me anymore.
Anyway, I adjusted the code a little and released [v0.7.3](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.7.3). Is it fixed now?

**Comment by Gazzoo-byte** [comment]
Appears to be resolved now, ty!
