### ISSUE TITLE
[Request] Portrait Catalogue

### ISSUE THREAD

**Issue by Eckoninja** [Haselnussbomber/HaselTweaks#140]
In addition to the currently implemented Portrait Preset Browser, would it be possible to implement a Portrait Catalogue of sorts where it would be possible to browse others' creations and download their configurations?

**Comment by Haselnussbomber** [comment]
I had this idea a long time ago, and this sounds like a simple thing to add at first, but to do it right it takes a lot of work and I'm just not motivated enough. Sorry.
