### ISSUE TITLE
[Feature Request] Forced Cutscene Voice

### ISSUE THREAD

**Issue by g0shu** [Haselnussbomber/HaselTweaks#141]
Same as `Forced Cutscene Music` but for voices.

**Comment by Haselnussbomber** [comment]
Yeah, that makes sense!
I've added configuration options to (the now renamed) Forced Cutscene Sounds to allow unmuting other audio channels and released it with [v30.0.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v30.0.0). 🙂
