### ISSUE TITLE
[Aether Current Helper] is extremely performance heavy

### ISSUE THREAD

**Issue by Mystic-W** [Haselnussbomber/HaselTweaks#142]
As the title says, Aether Current Helper is EXTREMELY performance heavy. As in, practically absurd. I feel like it might be in dire need of optimization.

On my setup, in Shaaloani, whenever I open the current helper, I go from 150 avg fps to 60. This is further exacerbated when I unhide already discovered currents, which makes them dip to almost 40.

**From here on, this is complete speculation. I have not reviewed the code as I'm not adept enough to understand complex projects yet.**
If I had access to further debug tools (e.g. hide specific currents) I could potentially pinpoint what I think is likely the culprit: the distance checks. I feel like they might either be handling absurd decimal precision for the coordinates, updating way too often, or both.

**Comment by Haselnussbomber** [comment]
Yeah, sorry about that! I didn't really look for that after the initial Lumina 5 update.
I've added a cache, so it doesn't have to look up the rows every frame anymore.
Released with [v30.0.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v30.0.2). 🙂
