### ISSUE TITLE
Incorrect aether current helper quest marker

### ISSUE THREAD

**Issue by justanity** [Haselnussbomber/HaselTweaks#15]
Quest marker should be "In Agama's Footsteps" instead of "Curing What Ails".

![TU6wue4gjk](https://user-images.githubusercontent.com/4033933/194251212-066295f7-3428-4671-bb22-c361f0fdb67c.png)

Upon completing "In Agama's Footsteps", aether current helper for "Curing What Ails" is marked as completed.

**Comment by alexanderneu** [comment]
well nice, logged in the wrong account on github 😅

**Comment by Hazado** [comment]
Did "The Hunter Becomes the Kweh" and it removed "Stolen Munitions" instead.

**Comment by Haselnussbomber** [comment]
Thanks! :)
