### ISSUE TITLE
East and West swapped in Aether Current Helper

### ISSUE THREAD

**Issue by jhessin** [Haselnussbomber/HaselTweaks#17]
Awesome plugin! Loads of great features. One issue I have found is when looking at the aether current helper The directions have East and West swapped - So if it says it's 100 yalms NE - it actually means 100 yalms NW and vice versa. North and South are correct though.

**Comment by Haselnussbomber** [comment]
Huh, lol. Guess I didn't notice that. 🤭
Thanks for reporting!

I'm currently not subscribed, so I can't verify and fix it right now, sorry.
Technically it should be just as simple as negating the second parameter of these vectors (just as a note for future self 😄):

https://github.com/Haselnussbomber/HaselTweaks/blob/cdc3d70e3e4b2cf6048623497e96bd90c438c262/Windows/AetherCurrentHelperWindow.cs#L419-L422

Will check this when I'll come back to the game. 🙂

**Comment by Haselnussbomber** [comment]
The free login campaign let me in and I fixed it (in v0.7.6 - just released). 🙂  Thanks again!
