### ISSUE TITLE
[Feature] Inventory Sort

### ISSUE THREAD

**Issue by 53m1k0l0n** [Haselnussbomber/HaselTweaks#21]
Well quite simple because you have it already for armory.

Sorting for inventory. I mean it should be basically copy paste and some little changes.

I mean i could spare me another plugin.

**Comment by Haselnussbomber** [comment]
Thanks for the PR! Released with [v0.8.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.8.0)! 🙂

I'll probably rework this in the future, so it's one tweak for all the sorting. 😆
Because retainer support would be nice too. 🤔🤪

**Comment by 53m1k0l0n** [comment]
Oh yeah retainer right, i mean it's basically the same.  ( saddlebag, rightsaddlebag, ) i'm not sure about these two.

**Comment by Haselnussbomber** [comment]
I couldn't resist and just did the rework. Check out [v0.9.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.9.0)!
Going to sleep now. Hopefully it works! :joy:
