### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Azuresk** [Haselnussbomber/HaselTweaks#23]
Since the update having hasel tweaks on is causing the game to crash. haven't checked each tweak individually for the source of crashes but I can guarantee its not the new ones atleast

**Comment by Haselnussbomber** [comment]
Hmm, I haven't encountered any crashes yet, but there was an issue with the PvPState (for the Enhanced Experience Bar).
I just released [v0.8.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.8.2) with a fix for that, can you check if it still crashes?

**Comment by Azuresk** [comment]
I dont understand how that was causing it but yeah the update seems to have fixed the crashing. Thanks for the prompt reply
