### ISSUE TITLE
Auto Sort Question

### ISSUE THREAD

**Issue by Dedoooo** [Haselnussbomber/HaselTweaks#24]
Would it be possible to have the auto sort have multiple options such as sort by Tab and Item level descending?
I really like how Tab works and making it sort by item level simultaneously would be amazing!

**Comment by Haselnussbomber** [comment]
No, that doesn't work, sorry.
The plugin doesn't do the sorting itself, but instead uses the built-in [/itemsort](https://eu.finalfantasyxiv.com/lodestone/playguide/db/text_command/a3840353abb/) command, just like you would use in a macro.
As far as I can see that command doesn't support multiple conditions.

**Comment by Haselnussbomber** [comment]
Actually, nevermind. It is possible. I JUST read the example in the german description which says it does exactly that, if you define multiple conditions before executing. I'll tweak the tweak a bit. :)

**Comment by Haselnussbomber** [comment]
Done! Check out [v0.9.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.9.1). 😃
