### ISSUE TITLE
[Suggestion] Save Portraits

### ISSUE THREAD

**Issue by PantsuPartyy** [Haselnussbomber/HaselTweaks#25]
How about a way to save multiple portrait settings? That way we can copy and paste them for when we need it again.

**Comment by Haselnussbomber** [comment]
Sorry, I didn't respond. I didn't feel like working on it for so long.
I've reworked the Portrait Helper, which now includes a Preset Browser! It's in [v0.14.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.14.0), which I just released.
Therefore, I'm closing this as complete. But feel free to report any bugs you find. 🙂
