### ISSUE TITLE
[Bug] Error in auto sorter

### ISSUE THREAD

**Issue by github-1348A55** [Haselnussbomber/HaselTweaks#26]
I used it with a JP client.
In Auto Sorter an error occurs when HQ is specified in the condition.
I think the error is due to the fact that the command is given as "HQ付き" in Japanese.

Also, in the category, no matter what condition or order is specified for the soul crystal, an error occurs.
I could not figure out why the sorting error occurs with soul crystals.

However, I think all of these problems can be fixed by using the standard commands. (alphabet only)

And without specifying any sorting conditions.
Is it possible to have the equivalent effect of performing the sort in the context menu on the game?
These are based on the in-game option settings.

**Comment by github-1348A55** [comment]
Thanks for the reply and update.
No problems with HQ and Soul Crystal were encountered and handled normally.

"Run All" is executed with "Auto Sorter" disabled, it is not sorted.
Then, when "Auto Sorter" was enabled, several lines of error messages... "Run All" Que remains?
This occurred only once and was not confirmed thereafter.

**Comment by Haselnussbomber** [comment]
Indeed, I forgot to clear the queue when the Tweak gets disabled. Thanks again!
I've released [v0.9.3](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.9.3) along with some other improvements. Hope everything is fine now. 🙂

**Comment by github-1348A55** [comment]
The problems I had with sorting are gone.
Possessions are always lined up correctly.

Thanks very much to you and this plugin!
