### ISSUE TITLE
[Bug] Right side shift key issue

### ISSUE THREAD

**Issue by github-1348A55** [Haselnussbomber/HaselTweaks#27]
Thank you for the other day.
I will report what I have noticed since then.

When deleting sort settings
The left shift key responds, but nothing responds to the right shift key.
This may be questionable for users who use the right shift key.

just noticed that...
If setup sorting on bag, will get an error when the bag is automatically opened in housing operation.
It seems that care must be taken in sorting the bags.

**Comment by Haselnussbomber** [comment]
Thanks again for reporting.

Sure, checking the right shift key makes sense.

You're right, during housing operations sorting doesn't work.
In fact, text commands are unavailable, just like during loading screens. Probably some limitation of the game.
Anyway, it took me 3 hours to figure out how to check for that. 😅
Now item sorting will be skipped when text commands aren't available.

I've released [v0.9.4](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.9.4) to address these issues.

**Comment by github-1348A55** [comment]
Amazed at the very energetic development and response.
I was able to confirm that both problems are gone.

It would have been easier sorting macro had used "/merror off"
But that means is not use available.
I think your efforts on this issue are excellent.

/clap & /cheer <Haselnussbomber>
