### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by githubuser14937** [Haselnussbomber/HaselTweaks#28]
After the new update, my game keeps crashing on load (or when I move to a new area) whenever I have HaselTweaks on. What do I need to report to help with this?

**Comment by Haselnussbomber** [comment]
Hmm. Would be helpful if you could upload the last "dalamud_appcrash_" files from the `%APPDATA%\XIVLauncher` folder.

**Comment by githubuser14937** [comment]
This is the last log file before the crash


> 2023-02-03 12:48:58.112 +13:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wMi0wM1QxMjo0ODo1OC4xMTI2OTUxKzEzOjAwIiwiSW5mbyI6IlN5c3RlbS5UeXBlTG9hZEV4Y2VwdGlvbjogQ291bGQgbm90IGxvYWQgdHlwZSAnRkZYSVZDbGllbnRTdHJ1Y3RzLkZGWElWLkNsaWVudC5HYW1lLk1KSU1hbmFnZXInIGZyb20gYXNzZW1ibHkgJ0ZGWElWQ2xpZW50U3RydWN0cywgVmVyc2lvbj0xLjAuMC4xNzA1LCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPW51bGwnLlxyXG4gICBhdCBIYXNlbFR3ZWFrcy5Ud2Vha3MuRW5oYW5jZWRFeHBCYXIuT25GcmFtZXdvcmtVcGRhdGUoRnJhbWV3b3JrIGZyYW1ld29yaylcclxuICAgYXQgSGFzZWxUd2Vha3MuUGx1Z2luLk9uRnJhbWV3b3JrVXBkYXRlKEZyYW1ld29yayBmcmFtZXdvcmspIGluIC9fL1BsdWdpbi5jczpsaW5lIDEwMlxyXG4gICBhdCBEYWxhbXVkLlV0aWxpdHkuRXZlbnRIYW5kbGVyRXh0ZW5zaW9ucy5IYW5kbGVJbnZva2UoQWN0aW9uIGFjdCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcVXRpbGl0eVxcRXZlbnRIYW5kbGVyRXh0ZW5zaW9ucy5jczpsaW5lIDk2IiwiQ29udGV4dCI6IkV4Y2VwdGlvbiBkdXJpbmcgcmFpc2Ugb2YgXCJWb2lkIDxJbnZva2VTYWZlbHk+Yl9fMCgpXCIifQ==
> 2023-02-03 12:48:58.112 +13:00 [ERR] Exception during raise of Void <InvokeSafely>b__0()
> System.TypeLoadException: Could not load type 'FFXIVClientStructs.FFXIV.Client.Game.MJIManager' from assembly 'FFXIVClientStructs, Version=1.0.0.1705, Culture=neutral, PublicKeyToken=null'.
>    at HaselTweaks.Tweaks.EnhancedExpBar.OnFrameworkUpdate(Framework framework)
>    at HaselTweaks.Plugin.OnFrameworkUpdate(Framework framework) in /_/Plugin.cs:line 102
>    at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96

**Comment by githubuser14937** [comment]
Here's the last dalamud_appcrash

[dalamud_appcrash_20230203_072536_348_25756.log](https://github.com/Haselnussbomber/HaselTweaks/files/10574359/dalamud_appcrash_20230203_072536_348_25756.log)

**Comment by Haselnussbomber** [comment]
Are you using Dalamud on the staging branch?

**Comment by githubuser14937** [comment]
i dont think so? it should auto update iirc. I never check. hahah will check now

**Comment by Haselnussbomber** [comment]
Because I'm seeing that it tries to use `FFXIVClientStructs.FFXIV.Client.Game.MJIManager`, but that got moved to `FFXIVClientStructs.FFXIV.Client.Game.MJI.MJIManager`.
If I update this, everyone using the stable branch will get that error until staging is pushed to stable.

**Comment by githubuser14937** [comment]
yeap it's on stg. didn't auto-update for some reason. Will try changing that and report!

**Comment by Haselnussbomber** [comment]
What I was saying is that HaselTweaks is not compatible with staging right now. Dalamud has to be on stable. Just to make that clear. 😄

**Comment by githubuser14937** [comment]
OOHHHHH lol. I thought my branch was old or something. sorryy!! misunderstood! okok thanks!
