### ISSUE TITLE
im dumb i think

### ISSUE THREAD

**Issue by leafyboilit** [Haselnussbomber/HaselTweaks#30]
idk how to get it to work in dalamund

**Comment by alexanderneu** [comment]
- Hit ESC and click on Dalamud Plugins.
- At the bottom left of the window, click the "Settings" button.
- Go to the "Experimental" tab.
- Scroll down to the "Custom Plugin Repositories" section and add: https://raw.githubusercontent.com/Haselnussbomber/MyDalamudPlugins/main/repo.json
- Click the "+" button.
- Click the checkbox to enable it.
- Click the round button bottom right to "Save changes and close".
- Then search for HaselTweaks and install it.
- Once enabled, you should be able to open the config using the cog wheel ("Open Configuration") right next to the enable switch, or with `/haseltweaks` in the chat.

**Comment by Haselnussbomber** [comment]
- Hit ESC and click on Dalamud Plugins.
- At the bottom left of the window, click the "Settings" button.
- Go to the "Experimental" tab.
- Scroll down to the "Custom Plugin Repositories" section and add: https://raw.githubusercontent.com/Haselnussbomber/MyDalamudPlugins/main/repo.json
- Click the "+" button.
- Click the checkbox to enable it.
- Click the round button bottom right to "Save changes and close".
- Then search for HaselTweaks and install it.
- Once enabled, you should be able to open the config using the cog wheel ("Open Configuration") right next to the enable switch, or with `/haseltweaks` in the chat.
