### ISSUE TITLE
Instance indicator not showing

### ISSUE THREAD

**Issue by Alkeyd** [Haselnussbomber/HaselTweaks#31]
![image](https://user-images.githubusercontent.com/94228374/218528181-99f3f6af-9d40-4fcd-aaa6-ebeb6ea8ba52.png)

**Comment by Alkeyd** [comment]
Iam at Radz-at-Han which still has two instances

**Comment by Haselnussbomber** [comment]
Yeah, you're right. This happend a while ago when I tried to optimize things.
Same problem with the busy status, which I fixed yesterday. I'll fix it really quick!

**Comment by Haselnussbomber** [comment]
Fixed in [v0.9.7](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.9.7) (just released). 🙂
