### ISSUE TITLE
Window lock tweak question

### ISSUE THREAD

**Issue by Dedoooo** [Haselnussbomber/HaselTweaks#32]
Would it be possible to have an option to lock all types of windows instead of manually having to set it up one by one?

Thank you for the great work and QoLs!

**Comment by Haselnussbomber** [comment]
Added and released with [v0.11.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.11.1)! Just hit the "Update plugins" button in Dalamud. 😉
