### ISSUE TITLE
[Bug] Pressing ESC after switching Jobs leads to CTD

### ISSUE THREAD

**Issue by Rueby** [Haselnussbomber/HaselTweaks#34]
Steps taken to crash
-Open Character Panel
-Switch to a Job
-Press ESC
-Crash to desktop w/o any error

This started happening with the latest update, and it was not happening prior to the 6.36 because I'm used to pressing ESC to close the character panel during/after job switch and I had no issues before.

Edit : 
Pressing C to close the character panel does not result in a crash.

**Comment by Haselnussbomber** [comment]
Thanks for reporting! I can confirm that it crashes for me too. I'll have a look soon! 🙂

**Comment by Rueby** [comment]
Awesome, take your time! Thanks alot for your tweaks they're amazing <3

**Comment by Haselnussbomber** [comment]
Should be fixed now! Released with [v0.12.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.12.0) along with a reworked tweak (Refresh Material List -> Enhanced Material List). 😄🎉

**Comment by Rueby** [comment]
Works flawlessly! No more crashes wooo thanks aloooot 🎉
