### ISSUE TITLE
PVP Exp bar

### ISSUE THREAD

**Issue by Alkeyd** [Haselnussbomber/HaselTweaks#35]
Hi again!

This function is not working =/

![image](https://user-images.githubusercontent.com/94228374/224758725-f265d911-f201-4163-aa47-dcacf66f16ce.png)

**Comment by Haselnussbomber** [comment]
Thanks for reporting. I found the mistake. Sorry about that. Will be fixed soon!

**Comment by Alkeyd** [comment]
Thank you! <3

**Comment by Haselnussbomber** [comment]
I've released [v0.12.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.12.1). It should work again. 🙂

**Comment by Alkeyd** [comment]
Yes, working again! Thank you!
