### ISSUE TITLE
[Bug] Character Class Switcher doesn't work with the DoH

### ISSUE THREAD

**Issue by iipom** [Haselnussbomber/HaselTweaks#38]
I'm able to switch between any DoW, DoM, and DoL, but the functionality is broken for the DoH

**Comment by iipom** [comment]
I don't, that could be the problem

**Comment by Haselnussbomber** [comment]
Okay, I found out that the game disables the buttons when desynthesis is not unlocked. So... I just enable them again after the game ran its update function. 😁
Please check out [v0.13.3](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.13.3) (you can just check for updates in Dalamud) and see if it works!

**Comment by iipom** [comment]
Yep, v0.13.3 fixes the issue. Thanks!

**Comment by Haselnussbomber** [comment]
Cool! 👍
Closing the issue then. 🙂
