### ISSUE TITLE
Auto-Sort not working when opening containers 

### ISSUE THREAD

**Issue by mkm-o** [Haselnussbomber/HaselTweaks#39]
Specifically, bag, armoury? It works in Retainer mode however.

**Comment by Haselnussbomber** [comment]
Oops. Yes, I made an internal change as to how windows are detected.
I'll fix it soon, sorry!

**Comment by Haselnussbomber** [comment]
Alright, I released [v0.13.4](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v0.13.4) which should fix it.

I was looking for a better way, which is why it took so long, but I couldn't find any, so it will - once again - check the visibility of the inventory on every frame. 🤷‍♂️
