### ISSUE TITLE
Thank you for the plugin!

### ISSUE THREAD

**Issue by seathasky** [Haselnussbomber/HaselTweaks#4]
I know it's a simple plugin, but I really love it!

Just wanted to show my appreciation.

**Comment by Iaotle** [comment]
yep it's pretty great

**Comment by Maxunit** [comment]
I want to thank you for HaselTweaks as well. It contains a couple tweaks I always wanted to see in SimpleTweaks, which it still lacks. It is one of my must-have plugins by now.

**Comment by Mat-G** [comment]
Just wanted to say thanks for the plugin, I was going crazy trying to find a way to unmute the background music in cutscenes! 
Such a great feature,
