### ISSUE TITLE
[Suggestion] More scrollable tabs

### ISSUE THREAD

**Issue by SayuShira** [Haselnussbomber/HaselTweaks#45]
Hey 👋 
I LOVE the scrollable tabs. So much in fact, I noticed myself trying to scroll in windows that don't support it (yet, i hope >.<).

Mainly the currency window. How many scrips do I have? Oh, I'm on the Tomes page. Do I need to spend tomes? Oh wrong tab.

Another one is the saddlebag.
You get the right saddlebag with the companion app. (Which might be an issue trying to implement and test it I guess?)
Its just kinda weird for me, as i can scroll every other inventory.

tl;dr:
- Currency window
- Chocobo saddlebag

---

On a side note:
With the "Open All" inventory, if you end up hovering over the box where the crystals are displayed in your inventory. Not the individual crystals, even just the space around, you can't scroll back. It works with "Expanded" inventory. I saw that there is a case for this in the code, that Expanded and OpenAll use the same i think, but maybe that's old info? `case "InventoryCrystalGrid":`

---

If there's any way I can help I'll of course.
I'm actually trying to understand whats going on in some plugins, but it's hard, being new to C# and to the whole Signatures, Reverse Engineered Structures things.

At end, in any case, thank you for enabling me to scroll through the game!

**Comment by Haselnussbomber** [comment]
Heya,

nice to hear! 😊 It's actually a feature that I brought over from World of Warcraft. It was just too convenient to not add it to FFXIV. 😉

I've just released [v14.10.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v14.10.0) which adds support for the Chocobo Saddlebag and Currency windows, as well as fixing the crystal grid issue (thanks for reporting!). 🎉

If there are any other windows (other than the Free Company ones - I'm a lone wolf) that you would like support for, or if you encounter any problems, please let me know.

Have a nice day! 🙂

**Comment by SayuShira** [comment]
That was so fast!
Thank you very much! I was already able to make use of it 😄 

If i notice or am missing something, I will write again 👍

**Comment by SayuShira** [comment]
Should I open a new issue or keep going here? I decided here for now and hope you see it >.<

Thanks again! It's amazing to scroll through Chocobo Saddlebad. And even the Character menu is scrollable now <3

But it is also the reason I'm writing to you again. I noticed that if you are in your retainer inventory and open the Chocobo Saddlebad it doesn't scroll. Seems to be some different internal window or something.
![image](https://github.com/Haselnussbomber/HaselTweaks/assets/104025906/8447e3fd-5a26-4a6e-a967-983c53742ac3)

**Comment by Haselnussbomber** [comment]
It's fine here. I don't care that much. 🙂

And you're right: It's a separate window, called `InventoryBuddy2`, because reasons. 🙄
I've added it to the tweak and released [v16.0.4](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v16.0.4)!

Thanks for reporting! 😊

**Comment by SayuShira** [comment]
You are amazing.

Thank you so much.
