### ISSUE TITLE
Custom Chat Timestamp not working

### ISSUE THREAD

**Issue by EmilyNyx** [Haselnussbomber/HaselTweaks#48]
No matter what I attempt to set it to, it displays the default timestamp in chat.

**Comment by Haselnussbomber** [comment]
Heya,
sorry about that! I just released [v15.1.3](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v15.1.3), which fixes it.
Simply hit "Update Plugins" in the Plugin Installer. :)
