### ISSUE TITLE
Feature Request: 'Search the Market' from 'Supply Mission' window

### ISSUE THREAD

**Issue by drejjmit** [Haselnussbomber/HaselTweaks#49]
Would it be possible to have 'Search the market' option here. Just like how 'Item Vendor Location' and 'GatherBuddy' does it?
![image](https://github.com/Haselnussbomber/HaselTweaks/assets/15526476/b9bb303b-b4ae-43fb-b2fb-7ad8b98f8564)

**Comment by Haselnussbomber** [comment]
Yep, added (in [v15.2.0](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v15.2.0)). 🙂
