### ISSUE TITLE
Crafters with ilvl 0 not working

### ISSUE THREAD

**Issue by Iaotle** [Haselnussbomber/HaselTweaks#5]
![image](https://user-images.githubusercontent.com/43072246/165692884-2630cb5d-9da7-45a4-994a-32f683856aaa.png)
![image](https://user-images.githubusercontent.com/43072246/165692901-f65832e8-9cbc-4dd3-b9a4-3565a3454445.png)

**Comment by Haselnussbomber** [comment]
Yep, didn't think of that. Fixed! 😃
