### ISSUE TITLE
Auto-sort unfocuses armory chest window

### ISSUE THREAD

**Issue by mogol1** [Haselnussbomber/HaselTweaks#55]
With the newest update, the armory chest window does not maintain focus after opening it while the auto sorter option is on. I play on controller so this means every time I open the armory chest, I have to press select to refocus the window before I can interact with it. This issue does not occur when Auto Sorter is off, or when HaselTweaks as a whole is off.

**Comment by Haselnussbomber** [comment]
I released [v16.0.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v16.0.1) with a fix for this. Thanks for reporting this! 👍
