### ISSUE TITLE
Enhanced login pet(fairy) model issue.

### ISSUE THREAD

**Issue by LaaZa** [Haselnussbomber/HaselTweaks#59]
For some reason the "pet" I get for scholar with the pet option enabled is a magitek drill mech instead of the fairy. I have Selene glamour.

Summoner and carbuncle works normally.

![mech](https://github.com/Haselnussbomber/HaselTweaks/assets/6142286/1b90d483-e590-4149-a35f-330fd1a1f47f)

**Comment by Haselnussbomber** [comment]
Hilarious! :joy:
I just went through all the pet glamours and fixed the ids (8eca6c70). Please update to [v16.1.3](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v16.1.3) and have a look. 🙂
