### ISSUE TITLE
Crashes FFXIV on character screen

### ISSUE THREAD

**Issue by githubuser14937** [Haselnussbomber/HaselTweaks#69]
The emote on the Character Screen is causing a Game Crash! (pls tell me what to do to provide more info, I'm not a techy person :3)

**Comment by Haselnussbomber** [comment]
Hmm, it works fine for me. 😳
I'm not sure actually. Maybe you could tell me which emote you picked. 🤔

**Comment by githubuser14937** [comment]
I'm using Bee's Knees

**Comment by Haselnussbomber** [comment]
Yep, can confirm it's crashing. I'll look into it!

**Comment by Haselnussbomber** [comment]
Alright, I fixed it. Still no idea how it didn't crash me. :joy:
Please update to [v18.0.1](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v18.0.1). 🙂

**Comment by githubuser14937** [comment]
was it just Bee's Knees? or every other emote but the one you were using?😂 
Done, will try now and report back

**Comment by Haselnussbomber** [comment]
I didn't test it with other emotes, but it definitely should work now.
But it also definitely should've crashed for me, using `/welcome`. Maybe just pure luck. 🤷‍♂️

All good then. Closing this and pushing another update, because I found some other place has it wrong too (in Portrait Helper). 😅

**Comment by githubuser14937** [comment]
HAHAHAHA I'm glad to have crashed? i guess.. LOL in any case, have a good one!

**Comment by Haselnussbomber** [comment]
You too! And thanks for reporting! 🙂
It really helps. Otherwise things go unnoticed and I have to read it up on some random websites comments in a different language again. (Yes, that happened! :rofl:)
