### ISSUE TITLE
[BUG] Selcting Miner in the character sheet using a controller switches to WHM instead

### ISSUE THREAD

**Issue by colopatiron** [Haselnussbomber/HaselTweaks#77]
Sometimes, selecting Miner with a controller in the character sheet switches you to WHM instead of miner. I haven't tested with a mouse.

**Comment by Haselnussbomber** [comment]
Hmm, I'm not sure. Seems to work fine for me in a quick test.
You could check your gear sets to see if something isn't right. The tweak goes through them all, checks their class/job id and then equips the one with the highest average item level.
Or maybe you have another plugin writing weird stuff into gear set data? 🤔
