### ISSUE TITLE
[Portrait Helper] Two minor issues

### ISSUE THREAD

**Issue by F-a-y-t-h** [Haselnussbomber/HaselTweaks#91]
Errorly reports 'Current appearance and/or gear does not match that shown in portrait' in many gear sets 

and a slight paranoia moment in that presets don't confirm if you own a emote (maybe also background and frame didn't try) before setting them.

**Comment by Haselnussbomber** [comment]
Heya,

the game stores a hash of the gear and appearance used in a portrait. My plugin generates said hash, based on your currently equipped gear and appearance and compares it to what is stored in the portrait. This hash is composed of item ids (glamour item ids have priority) and dyes of all 14 slots (don't get confused: one of these is the old belt slot, which will be 0), the headgear visibility, the weapon visibility and if your visor is open or closed. If any of these are not the same as when the portrait was saved, the hash won't match and the error will be shown. So please make sure everything matches. 😊

And yes, you're right, the plugin does currently not check if anything in the preset is actually unlocked on the character. I'll have a look at it.

**Comment by F-a-y-t-h** [comment]
im not sure how i can debug what causing the mismatch error; i tried remaking a gearset and tried remaking the portrait

pld (but not glad), war (but not maruda) white, bard (and archer..oddly), redmage and reaper are the ones that the error wont go away with no matter what i attempted to do sofar

**Comment by Haselnussbomber** [comment]
Did you link the gearsets with a glamour plate or are they unlinked?

**Comment by Haselnussbomber** [comment]
Please check out [v20.3.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v20.3.2).
The plugin now calls a function from the game to gather the list of equipped items and their dyes.
Since this is now 100% the game's code, it should fix the problem?

**Comment by F-a-y-t-h** [comment]
Seems to be working now

**Comment by Haselnussbomber** [comment]
Cool!
Thank you for asking about it. I always wanted to add some extra checks, but never got around to do it.
I'm gonna close the issue then. If there is anything else, just leave comment. 🙂
