### ISSUE TITLE
scrollable tabs crashes the game when scrolling beyond last tab in retainer inventory

### ISSUE THREAD

**Issue by LastExceed** [Haselnussbomber/HaselTweaks#98]
repro:
* enable scrollable tabs
* open the inventory of  a retainer
* go to the last tab
* scroll 1 step further

amazing plugin btw, thanks for your effort

**Comment by Haselnussbomber** [comment]
Are you using the chinese dalamud fork? It’s out of date by 3 weeks.

**Comment by LastExceed** [comment]
no, but now that you mention it i might still be on the stg branch from beta-testing. i'll check that

**Comment by Haselnussbomber** [comment]
Needs to be at least Dalamud 9.1.0.8.
But maybe I copy pasted the number of tabs wrong during the cleanup. I’ll check soon, whenever I’m on my PC. :)

**Comment by LastExceed** [comment]
problem persists on stable branch (9.1.0.9)

**Comment by LastExceed** [comment]
not if i fix it first!

**Comment by Haselnussbomber** [comment]
Fixed in [v23.0.2](https://github.com/Haselnussbomber/HaselTweaks/releases/tag/v23.0.2). Thanks for reporting!
